export const CATEGORIES = [
    { id: 'maintenance', he: 'אחזקה', en: 'Maintenance' },
    { id: 'vehicle_maintenance', he: 'אחזקת רכב', en: 'Vehicle Maintenance' },
    { id: 'fuel', he: 'דלק', en: 'Fuel' },
    { id: 'parking', he: 'חניה', en: 'Parking' },
    { id: 'vehicle_insurance', he: 'ביטוח רכב', en: 'Vehicle Insurance' },
    { id: 'vehicle_license', he: 'רישיון רכב', en: 'Vehicle License' },
    { id: 'vehicle_rental', he: 'השכרת רכב', en: 'Vehicle Rental' },
    { id: 'internet', he: 'אינטרנט', en: 'Internet' },
    { id: 'home_insurance', he: 'ביטוח דירה', en: 'Home Insurance' },
    { id: 'property_tax', he: 'ארנונה', en: 'Property Tax' },
    { id: 'water', he: 'מים', en: 'Water' },
    { id: 'electricity', he: 'חשמל', en: 'Electricity' },
    { id: 'mobile_phone', he: 'טלפון נייד', en: 'Mobile Phone' },
    { id: 'refreshments', he: 'כיבודים', en: 'Refreshments' },
    { id: 'professional_insurance', he: 'ביטוח מקצועי', en: 'Professional Insurance' },
    { id: 'education', he: 'ספרות והשתלמות', en: 'Education' },
    { id: 'professional_services', he: 'שירותים מקצועיים', en: 'Professional Services' },
    { id: 'rent', he: 'שכירות', en: 'Rent' },
    { id: 'office_supplies', he: 'משרדיות', en: 'Office Supplies' },
    { id: 'consumables', he: 'ציוד מתכלה', en: 'Consumables' },
    { id: 'hoa_fees', he: 'ועד בית', en: 'HOA Fees' },
    { id: 'fixed_assets', he: 'רכוש קבוע', en: 'Fixed Assets' },
    { id: 'other', he: 'אחר', en: 'Other' },
];
